name:                gossip-haskell
version:             0.1.0.0
github:              "sakshamsharma/gossip-haskell"
license:             BSD3
author:              "Saksham Sharma"
maintainer:          "saksham0808@gmail.com"
copyright:           "2018 Saksham Sharma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/sakshamsharma/gossip-haskell#readme>

dependencies:
- abstract-network
- base >= 4.7 && < 5
- bytestring
- cereal >= 0.5 && <0.6
- containers
- cryptonite
- mtl
- stm
- threads
- time
- transformers
- unagi-chan
- unordered-containers

library:
  source-dirs: src
  default-extensions:
  - RecordWildCards

executables:
  gossip-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gossip-haskell

tests:
  gossip-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gossip-haskell
